import CONSTANT from '@/configs/constant'
const config = {
  googleReCaptchaKey: '6LdPM8MUAAAAAEc7SNWoA-KN4IH_sR_Rgwsb5gLk',
  KEYCLOAK_OPTS_URL: process.env.VUE_APP_KEYCLOAK_OPTS_URL,
  KEYCLOAK_OPTS_REALM: process.env.VUE_APP_KEYCLOAK_OPTS_REALM,
  KEYCLOAK_OPTS_CLIENT_ID: process.env.VUE_APP_KEYCLOAK_OPTS_CLIENT_ID,
  BASE_URL_OAUTH: process.env.VUE_APP_BASE_URL_OAUTH,
  BASE_URL_OAUTH_CLIENT_ID: process.env.VUE_APP_BASE_OAUTH_CLIENT_ID,
  BASE_URL_API: process.env.VUE_APP_BASE_URL_API,
  BASE_URL_PROXY: process.env.VUE_APP_BASE_URL_PROXY,
  BASE_URL_SIGNALR_OTC_SOCKET: process.env.VUE_APP_BASE_URL_SIGNALR_OTC_SOCKET,
  EXTERNAL_URL: {
    EXCHANGE_URL: process.env.VUE_APP_EXCHANGE_DOMAIN + CONSTANT.EXTERNAL_PATH.EXCHANGE_PATH,
    MARKET_URL: process.env.VUE_APP_EXCHANGE_DOMAIN + CONSTANT.EXTERNAL_PATH.MARKET_PATH,
    EXCHANGE_ACCOUNT: process.env.VUE_APP_EXCHANGE_DOMAIN + CONSTANT.EXTERNAL_PATH.EXCHANGE_ACCOUNT_PATH,
    MAIN_ACCOUNT: process.env.VUE_APP_WALLET_DOMAIN + CONSTANT.EXTERNAL_PATH.MAIN_ACCOUNT_PATH,
    EXCHANGE_ORDERS: process.env.VUE_APP_EXCHANGE_DOMAIN + CONSTANT.EXTERNAL_PATH.EXCHANGE_ORDERS,
    KYC: process.env.VUE_APP_BASE_URL_OAUTH + CONSTANT.EXTERNAL_PATH.KYC,
    REGISTER: process.env.VUE_APP_BASE_URL_OAUTH + CONSTANT.EXTERNAL_PATH.REGISTER,
    CHANGEPASS: process.env.VUE_APP_BASE_URL_OAUTH + CONSTANT.EXTERNAL_PATH.CHANGEPASS,
    PROFILE: process.env.VUE_APP_BASE_URL_OAUTH + CONSTANT.EXTERNAL_PATH.PROFILE,
    INVITATION: process.env.VUE_APP_BASE_URL_OAUTH + CONSTANT.EXTERNAL_PATH.INVITATION
  },
  EXCHANGE_DOMAIN: process.env.VUE_APP_EXCHANGE_DOMAIN
}

export default config
